spring:
  h2:
    console:
      enabled: true
      path: /console
  liquibase:
    password: ''
    user: sa
    change-log: classpath:db/changelog/changelog-master.xml
  datasource:
    url: jdbc:h2:mem:stock_tests
    username: sa
    password: ''
    driverClassName: org.h2.Driver
  sql:
    init:
      platform: h2
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
server:
  port: 8090
